import type { Metadata } from "next";
import "./globals.css";
import Header from "./HeaderFullNav";
import Footer from "./Footer";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
    <html lang="en">
      <body className="bg-gradient-to-r from-cyan-500 to-blue-500">
      <Header/>
      {children}
      <Footer/>
      </body>
    </html>
    </>
  );
}
